### ISSUE TITLE
Debian 8 pip compatibility?

### ISSUE THREAD

**Issue by agneal** [osuosl/ganeti_webmgr#108]
I've installed all of the dependencies, but the setup.sh script fails when it reaches /opt/ganeti_webmgr/bin/pip

Have tried reinstalling pip in various ways. Does it only work with older versions of pip now?

it breaks on "from pip import main" and produces the error:

``` Traceback (most recent call last):                                                                                        File "/opt/ganeti_webmgr/bin/pip", line 7, in <module>                                                                    from pip import main                                                                                                  File "/opt/ganeti_webmgr/local/lib/python2.7/site-packages/pip/__init__.py", line 76, in <module>                         from pip.commands import commands, get_summaries, get_similar_commands                                                File "/opt/ganeti_webmgr/local/lib/python2.7/site-packages/pip/commands/__init__.py", line 6, in <module>                 from pip.commands.bundle import BundleCommand                                                                         File "/opt/ganeti_webmgr/local/lib/python2.7/site-packages/pip/commands/bundle.py", line 6, in <module>                   from pip.commands.install import InstallCommand                                                                       File "/opt/ganeti_webmgr/local/lib/python2.7/site-packages/pip/commands/install.py", line 5, in <module>                  from pip.req import InstallRequirement, RequirementSet, parse_requirements                                            File "/opt/ganeti_webmgr/local/lib/python2.7/site-packages/pip/req/__init__.py", line 3, in <module>                      from .req_install import InstallRequirement                                                                           File "/opt/ganeti_webmgr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 42, in <module>                  from pip.utils.hashes import Hashes                                                                                   File "/opt/ganeti_webmgr/local/lib/python2.7/site-packages/pip/utils/hashes.py", line 5, in <module>                      from pip.exceptions import HashMismatch, HashMissing, InstallationError                                             ImportError: cannot import name HashMissing                                                                             Something went wrong. Could not install GWM nor its dependencies                                                        in this virtual environment:                                                                                              /opt/ganeti_webmgr    ```

**Comment by agneal** [comment]
attaching image of error output for better formatting 
![gwm-pip](https://user-images.githubusercontent.com/2626068/56996761-995e0e80-6b73-11e9-84d6-5187ebe2a422.PNG)

**Comment by ramereth** [comment]
@agneal it likely only works on older versions of pip unfortunately. See if you try that and it works.
